version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: numgen
    ports:
       - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./dockerScripts/postgres:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:16.0.0
    ports:
      - 10001:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_USER: keycloak
      DB_PASSWORD: password
    networks:
      - keycloak-network

networks:
  keycloak-network: